server/twitinfo/urls.py
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('server.twitinfo.views',
    (r'^$', 'twitinfo'),
    (r'^results', 'search_results'),
    (r'^detail/(?P<event_id>\d+)/$', 'event_details'),
    (r'^create_event/$', 'create_event'),
    (r'^detail/create_graph/(?P<event_id>\d+)/$', 'create_graph'),
    (r'^detail/create_piChart/(?P<event_id>\d+)/$', 'create_pieChart'),
    (r'^detail/create_map/(?P<event_id>\d+)/$', 'create_map'),
    (r'^display_tweets/(?P<event_id>\d+)/$', 'display_tweets'),
    (r'^display_links/(?P<event_id>\d+)/$', 'display_links'),
)

server/urls.py
from django.conf.urls.defaults import *
import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'^admin/', include(admin.site.urls)),
    (r'^static/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.STATIC_DOC_ROOT}),
    (r'^', include('server.twitinfo.urls')),
)

server/twitinfo/models.py
from django.db import models
from django import forms

class Tweet(models.Model):
    id = models.AutoField(primary_key=True, db_column="__id")
    tweet = models.TextField(db_column="text")
    user_id = models.IntegerField(default=0)
    screen_name = models.TextField(default="")
    created_at = models.DateTimeField('created date', db_index=True)
    sentiment = models.FloatField(db_column='sent')
    profile_image_url = models.TextField()
    location = models.TextField(null=True)
    latitude = models.FloatField(null=True)
    longitude = models.FloatField(null=True)

    class Meta:
        db_table = 'tweets_from_keywords'
    def __unicode__(self):
        return self.tweet

class Keyword(models.Model):
    key_word = models.CharField(max_length=200, unique=True)
    tweets = models.ManyToManyField(Tweet)
    max_indexed = models.IntegerField(default=-1)
    
    
    @staticmethod   
    def normalize_keywords(keywords):
        """
            takes in a comma separated string of keywords and returns a list of normalized keywords.
        """
        list_keywords=[]
        k=keywords.split(',')
        for key in k:
            filtered_key = Keyword.normalize(key)
            list_keywords.append(filtered_key)
        return list_keywords

    @staticmethod
    def normalize(kw):
        return (' '.join(kw.split())).lower()
        
    def __unicode__(self):
        return self.key_word

    
class Event(models.Model):
    featured = models.BooleanField(default=False)
    name = models.CharField(max_length=200)
    start_date = models.DateTimeField(null=True, blank=True)
    end_date = models.DateTimeField(null=True, blank=True)
    keywords = models.ManyToManyField(Keyword)
    children = models.ManyToManyField("self", symmetrical=False, related_name='parents', blank=True)
    def __unicode__(self):
        return self.name
    
    @staticmethod   
    def normalize_name(name):
        return (' '.join(name.split())).lower()
    

class WordFrequency(models.Model):
    word = models.CharField(max_length=300)
    idf = models.FloatField()

server/twitinfo/views.py
from django import forms
from django.shortcuts import get_object_or_404, render_to_response
from django.http import HttpResponseRedirect, HttpResponse
from django.core.cache import cache
from django.core.context_processors import csrf
from django.core.urlresolvers import reverse
from django.db.models import Avg, Max, Min, Count, Sum, F
from django.template import RequestContext, Context, Template, loader
from django.views.decorators.cache import cache_page
from server.twitinfo.models import Event,Tweet,Keyword,WordFrequency
from datetime import datetime,timedelta
from operator import itemgetter
import itertools
import json
import nltk
import re
import random
import sys
import settings
sys.path.append(settings.SSQL_PATH)
from ssql.builtin_functions import MeanOutliers

NUM_TWEETS = 20 # total tweets to display
NUM_LINKS = 3 # total top links to display
URL_REGEX = re.compile("http\:\/\/\S+")
CACHE_SECONDS = 864000

def twitinfo(request):
    featured = Event.objects.filter(featured = True)
    return render_to_response('twitinfo/twitinfo.html', {"featured":featured})
       
def search_results(request):
    search = Event.normalize_name(request.GET['query'])
    events = Event.objects.filter(name = search)
    events_from_keywords = Event.objects.filter(keywords__key_word=search)
    total_events=itertools.chain(events,events_from_keywords)
    total_events=list(total_events)
    if len(total_events)==0:
        return render_to_response('twitinfo/results.html', {'error':'Sorry, the keyword you searched for does not exist.'},
                                 context_instance=RequestContext(request))
    else:
        return render_to_response('twitinfo/results.html', {'events':total_events},
                               context_instance=RequestContext(request))
                                   
def event_details(request,event_id):
    try:
       keys=[]
       event = Event.objects.get(pk=event_id)
       keywords = Keyword.objects.filter(event=event_id).values_list('key_word', flat=True)
       keys=", ".join(keywords)
    except Event.DoesNotExist:
        return render_to_response('twitinfo/details.html', {'error':'Event does not exit!'},
                                 context_instance=RequestContext(request))
  
    return render_to_response('twitinfo/details.html', {'event':event,'keywords':keys},
                                  context_instance=RequestContext(request))

class TweetDateForm(forms.Form):
    start_date = forms.DateTimeField(input_formats=["%Y-%m-%d %H:%M"],required=False)
    end_date = forms.DateTimeField(input_formats=["%Y-%m-%d %H:%M"],required=False)
    words = forms.CharField(required=False)

def display_tweets(request,event_id):
    key = request.get_full_path()
    print "fp: %s" % key
    resp_string = cache.get(key)
    if resp_string == None:
        print "no cache"
        resp_string = display_tweets_impl(request, event_id)
        cache.set(key, resp_string, CACHE_SECONDS)
    print "after getting data"
    return HttpResponse(resp_string)

def display_tweets_impl(request,event_id):
    try:
       print "before"
       event = Event.objects.get(pk=event_id)
       print "uh"
    except Event.DoesNotExist:
        return render_to_response('twitinfo/display_tweets.html', {'error':'Event does not exit!'},
                                 context_instance=RequestContext(request))
    tweets = Tweet.objects.filter(keyword__event=event_id)
    print "generated tweets query"
    form = TweetDateForm(request.REQUEST)
    if form.is_valid():
        print "getting date data"
        start_date = form.cleaned_data['start_date']
        end_date = form.cleaned_data['end_date']
        start_date = start_date if start_date != None else event.start_date
        end_date = end_date if end_date != None else event.end_date
        if start_date != None:
            tweets = tweets.filter(created_at__gte = start_date)
        if end_date != None:
            tweets = tweets.filter(created_at__lte = end_date)
        tweets = tweets.order_by("created_at")#+
        words = form.cleaned_data['words']
        if len(words) == 0:
            print "no words"
            tweets = tweets[:NUM_TWEETS]
        else:
            print "splitting tweets"
            words = words.split(",")
            matched_tweets = []
            already_tweets = set()
            for tweet in tweets[:500]:
                count = 0
                text = tweet.tweet.lower()
                if "rt" in text:
                    count -= 2
                text = URL_REGEX.sub("WEBSITE", text)
                if text not in already_tweets:
                    for word in words:
                        if word in text:
                            count += 1
                    matched_tweets.append((tweet, count))
                    already_tweets.add(text)
            matched_tweets.sort(cmp=lambda a,b: cmp(b[1],a[1]))
            tweets = [t[0] for t in matched_tweets[:min(NUM_TWEETS,len(matched_tweets))]]
        t = loader.get_template('twitinfo/display_tweets.html')
        print len(tweets)
        resp_string = t.render(Context({'tweets': tweets,'event':event}))
        return resp_string

def display_links(request,event_id):
    key = request.get_full_path()
    resp_string = cache.get(key)
    if resp_string == None:
        resp_string = display_links_impl(request, event_id)
        cache.set(key, resp_string, CACHE_SECONDS)
    return HttpResponse(resp_string)

def display_links_impl(request,event_id):
    try:
       event = Event.objects.get(pk=event_id)
    except Event.DoesNotExist:
        return 'Event does not exit!'
    tweets = Tweet.objects.filter(keyword__event=event_id)

    form = TweetDateForm(request.REQUEST)
    if form.is_valid():
        start_date = form.cleaned_data['start_date']
        end_date = form.cleaned_data['end_date']
        start_date = start_date if start_date != None else event.start_date
        end_date = end_date if end_date != None else event.end_date
        if start_date != None:
            tweets = tweets.filter(created_at__gte = start_date)
        if end_date != None:
            tweets = tweets.filter(created_at__lte = end_date)
        tweets = tweets.order_by("created_at")#+
        links = {}
        for tweet in tweets[:500]:
            text = tweet.tweet
            incr = 1
            if "RT" in text:
                incr = .5
            for match in URL_REGEX.findall(text):
                count = links.get(match, 0.0)
                count += incr
                links[match] = count
        linkcounts = links.items()
        linkcounts.sort(key = itemgetter(1), reverse = True)
        displaylinks = []
        for i in range(0, min(len(linkcounts), NUM_LINKS)):
            if linkcounts[i][1] > 2.5:
                displaylinks.append((linkcounts[i][0], int(linkcounts[i][1])))
        t = loader.get_template('twitinfo/display_links.html')
        resp_string = t.render(Context({'links': displaylinks}))
        return resp_string
    
class EventForm(forms.Form):
    title=forms.CharField(max_length=100)
    key_words = forms.CharField()
    start_date = forms.DateTimeField(input_formats=["%Y-%m-%d %H:%M"],required=False)
    end_date = forms.DateTimeField(input_formats=["%Y-%m-%d %H:%M"],required=False)
    parent_id = forms.IntegerField(widget=forms.HiddenInput,required=False)
    

def create_event(request):
   if request.method == 'POST': # If the form has been submitted...
       form = EventForm(request.POST) # A form bound to the POST data
       if form.is_valid():
           name = form.cleaned_data['title']
           name = Event.normalize_name(name)
           key_words = form.cleaned_data['key_words']
           list_keywords = Keyword.normalize_keywords(key_words)
           keyobjs=[]
           for key in list_keywords:
               try:
                   fkeyword = Keyword.objects.get(key_word = key)
               except Keyword.DoesNotExist:
                   fkeyword = Keyword(key_word = key)
                   fkeyword.save() 
               keyobjs.append(fkeyword)  
           
           e = Event(name = name,start_date = None,end_date = None)
           try:
               e.start_date = form.cleaned_data['start_date']
           except:
               pass
           try:
               e.end_date = form.cleaned_data['end_date']
           except:
               pass
           e.save()
           e.keywords = keyobjs
           try:
               parent = form.cleaned_data['parent_id']
               parent_event = Event.objects.get(id=parent)
               parent_event.children.add(e)
               cache.delete("graph" + str(parent)) # clear parent view to include child
           except Event.DoesNotExist:
               pass
           return HttpResponseRedirect('detail/%d' % (e.id)) # Redirect after POST
   else:
       # initialize the form with a set of values that are passed in as data. If there are no initial values,initialize an empty form.
       try:
           parent_id=request.GET["parent_id"]
           keywords=request.GET["keywords"]
           sd=request.GET["start_date"]
           ed=request.GET["end_date"]
           data={'start_date':sd,'end_date':ed,'key_words':keywords,'parent_id':parent_id,'title':" "}
           form = EventForm(data) 
       except:
           form = EventForm()
   return render_to_response('twitinfo/create_event.html', {'form': form}, context_instance=RequestContext(request))    
   

def find_end_dates(tweets,list_peaks):
    i=0
    k=0
    
    if len(list_peaks) > 0:
        while(i<len(list_peaks) and i+1<len(list_peaks)):
            for j in range(len(tweets)):
                if(list_peaks[i]["start_date"]==tweets[j]['date']):
                    k=j+1
                    break
            while(k<len(tweets)):

server/templates/twitinfo/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <!-- <link rel="stylesheet" href="style.css" /> -->
    <title>{% block title %}twitinfo{% endblock %}</title>
	<style type="text/css">

	input#button{
	 background-color :#D3D3D3;
	 border : 1px solid #000;
	 font-family: verdana;
	 font-size: 15px;
	 }

	div#hd {

	    border-bottom: 2px solid black;
	}
	div#hd #heading a {
		text-decoration:none;
		color:#0099FF;
	    margin-bottom: 1;
		font-size:22pt;
	}

	</style>
	{% block headblock %}{% endblock %}
</head>

<body onload="initialize()">
	<div id="hd">
		{% block heading %}
	    <span id="heading"><a href="/">twitInfo</a></span>
		{% endblock %}
	</div>
	<div id="content">
	  	{% block content %}{% endblock %}
	</div>
</body>
</html>

server/templates/twitinfo/create_event.html
{% extends "twitinfo/base.html" %}

{% block headblock %}

	<link type="text/css" href="/static/css/ui-lightness/jquery-ui-1.8.custom.css" rel="Stylesheet" />	
	<link type="text/css" href="/static/css/ui.timepickr.css" rel="Stylesheet" />	
	<script type="text/javascript" src="/static/js/jquery-1.4.2.min.js"></script>
	<script type="text/javascript" src="/static/js/jquery-ui-1.8.custom.min.js"></script>
	<script type="text/javascript" src="/static/js/jquery-ui-timepicker-addon-0.5.min.js"></script>
	

		<script type="text/javascript">
		$(function() {			
			$("#id_start_date").datetimepicker({ dateFormat: 'yy-mm-dd', timeFormat: 'hh:mm' });
			$("#id_end_date").datetimepicker({ dateFormat: 'yy-mm-dd', timeFormat: 'hh:mm' });
		});
		</script>

{% endblock %}

{% block content %}
<p><b>Create an event</b></p>
<form action="/create_event/" method="post">
{% csrf_token %}


<p>
<div class="fieldWrapper">
    {{ form.title.label_tag }}: {{ form.title }}
    {{ form.title.errors }}
</div>
</p>

<p>
<div class="fieldWrapper">
    {{ form.key_words.label_tag }}: {{ form.key_words }}
    {{ form.key_words.errors }}
</div>
</p>

<p>
<fieldset>
<legend>Advanced Settings (Optional)</legend>
{{ form.start_date.label_tag }}: {{ form.start_date }}
{{ form.start_date.errors }}
	    
{{ form.end_date.label_tag }}: {{ form.end_date }}
{{ form.end_date.errors }}
</fieldset>
</p>

</fieldset>

{{ form.parent_id }}

<input type="submit" value="Submit" id="button" />
</form>
</body>
</html>
{% endblock content %}

server/templates/twitinfo/create_graph.html
({% templatetag openbrace %}
	"cols": [{% templatetag openbrace %}'id': 'date','label':'DATE','type': 'datetime'{% templatetag closebrace %},{% templatetag openbrace %}'id': 'frequency','label':'FREQUENCY' ,'type': 'number'{% templatetag closebrace %},{% templatetag openbrace %}'id': 'title','label':'TITLE','type': 'string'{% templatetag closebrace %},{% templatetag openbrace %}'id': 'text','label':'TEXT','type': 'string'{% templatetag closebrace %}],
	"rows": [
		{% for tweet in tweets %}
			{% templatetag openbrace %}'c':[ {% templatetag openbrace %}'v':{{tweet.d}}{% templatetag closebrace %},{% templatetag openbrace %}'v':{{tweet.num_tweets}}{% templatetag closebrace %},{% templatetag openbrace %}'v':{{tweet.title|safe}}{% templatetag closebrace %},
		
			{% templatetag openbrace %}
			
			'v':
			{% if tweet.title != "null" %}
			'<!--<br><a href="/create_event?start_date={{tweet.data.start_date}}&end_date={{tweet.data.end_date}}&keywords={{tweet.data.keywords}}&parent_id={{tweet.data.event}}" target="_blank">Label this event</a><ul>{% for child in tweet.children %}<li><a href="/detail/{{child.id}}/" target="_blank">{{child.name}}</a></li>{% endfor %}</ul>-->'
			{% else %}null{% endif %}
			{% templatetag closebrace %}]
			
			{% templatetag closebrace %},
		{% endfor %}
	]
{% templatetag closebrace %});

server/templates/twitinfo/createtweets.html
<h3>great! tweets created</h3>

server/templates/twitinfo/details.html
{% extends "twitinfo/base.html" %}

	{% block headblock %}
		<script type='text/javascript' src='http://www.google.com/jsapi'></script>
		<!--<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>-->
		<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.js"></script>
        <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
		<script type="text/javascript" src="/static/js/date.js"></script>
		<style type="text/css">
			div#title #title {
			    font-size:16pt;
			}
			div#title .subheading {
				font-size:10pt;
			}
		</style>
			
		<script type='text/javascript'>
        	google.load('visualization', '1', {'packages':['annotatedtimeline']});
			google.load('visualization', '1', {'packages':["corechart"]});
            var old_infowindow = null;
			function initialize() {
                request_map("");
                request_graph();
                request_pie("");
			}
            function request_map(extra_args) {
				$.getJSON("/detail/create_map/{{event.id}}?jsoncallback=?&" + extra_args,
				          function(data){
						  	draw_map(data)
					 	  } 
				);
            }
            function request_graph() {
				$.getJSON("/detail/create_graph/{{event.id}}?jsoncallback=?",
				          function(data){
						  	draw_graph(data)
					 	  } 
				);
            }
            function request_pie(extra_args) {
				$.getJSON("/detail/create_piChart/{{event.id}}?jsoncallback=?&" + extra_args,
				          function(data){
						  	draw_piChart(data)
					 	  } 
				);
            }
			function draw_graph(data) {
			  var data = new google.visualization.DataTable(data,0.6);
			  var chart = new google.visualization.AnnotatedTimeLine(document.getElementById('chart_div'));
			  chart.draw(data, {displayAnnotations: true,allowHtml:true, annotationsWidth: 30, displayAnnotationsFilter: true});
              
              google.visualization.events.addListener(chart, 'select',
                function(event) {
                    row = chart.getSelection()[0].row;
                    create_link = data.getValue(row, 3);
                    arg_str = create_link.split("?")[1];
                    args = arg_str.split("&");
                    extra_args = args[0] + "&" + args[1];
//                    extra_args = extra_args + "end_date=" + formatDate(data.getValue(row,0), 'yyyy-MM-dd HH:mm');
                    request_pie(extra_args);
                    request_map(extra_args);
                    tweet_src = "/display_links/{{event.id}}?"
                    tweet_src = tweet_src + extra_args;
                    $("#links_iframe").attr("src", tweet_src);
                    tweet_src = "/display_tweets/{{event.id}}?"
                    tweet_src = tweet_src + extra_args;
                    words = data.getValue(row, 2);
                    words = words.replace(/ /g, "");
                    tweet_src = tweet_src + "&words=" + words;
                    $("#tweets_iframe").attr("src", tweet_src);
                });
            }	
			function draw_piChart(data) {
				var data = new google.visualization.DataTable(data,0.6);
				var chart = new google.visualization.PieChart(document.getElementById('pchart_div'));
				chart.draw(data, {displayAnnotations: true});
			}
            function draw_map(data) {
                var myLatlng = new google.maps.LatLng(39.095963,-97.031250);
                var myOptions = {
                  zoom: 1,
                  center: myLatlng,
                  mapTypeId: google.maps.MapTypeId.ROADMAP
                }
                var map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);
                for (var i = 0; i < data.length; i++) {
                    var tweet = data[i];
                    var icon = 'http://labs.google.com/ridefinder/images/mm_20_gray.png';
                    if (tweet.sentiment > 0) {
                        icon = 'http://labs.google.com/ridefinder/images/mm_20_blue.png';
                    } else if (tweet.sentiment < 0) {
                        icon = 'http://labs.google.com/ridefinder/images/mm_20_red.png';
                    }
                    var marker = new google.maps.Marker({
                        position: new google.maps.LatLng(tweet.latitude, tweet.longitude), 
                        map: map,
                        title: tweet.text,
                        icon: icon
                    });
                    attach_message(map, marker, tweet);
                }
            }
            
            function attach_message(map, marker, tweet) {
                content = "<div style='float: left;'><img src='" + tweet.image + "'></div>" + tweet.text;
                var infowindow = new google.maps.InfoWindow(
                    { content: content }
                );
                google.maps.event.addListener(marker, 'click', function() {
                    if (old_infowindow != null) {
                        old_infowindow.close();
                    }
                    infowindow.open(map,marker);
                    old_infowindow = infowindow;
                });
            }
		</script>
		{% endblock %}
{% block content %}
{% if error %}
    
	<p><strong>{{ error }}</strong></p>

{% else %}
	
		<div style="float: right; width: 30%;">
			<b>Relevant Tweets</b>
			<iframe src ="/display_tweets/{{event.id}}" id="tweets_iframe" width="100%" height="250">
		  		<p>Your browser does not support iframes.</p>
			</iframe>
			<div style="margin: 5px;">
			<b>Popular Links</b>
			</div>
            <iframe src ="/display_links/{{event.id}}" id="links_iframe" width="100%" height="80">
		  		<p>Your browser does not support iframes.</p>
			</iframe>
			<div style="margin: 5px;">
            <b>Overall Sentiment</b>
            </div>
			 <div id='pchart_div' style='width: 100%; height: 175px;'></div>
		</div> 

		<div id="title">
			<p>
			<span id="title">{{event.name}}</span><br>
			<span class="subheading">Keywords: {{keywords}}</span><br>
			<span class="subheading">Event dates: 
            {{ event.start_date|default_if_none:"no start"}} - 
            {{event.end_date|default_if_none:"no end" }}</span>
			</p>
		</div>

		<div style="float: left; width: 70%;">
			 <div><b>Message Frequency</b></div>
			 <div id='chart_div' style='width: 100%; height: 240px;'></div>
			 <div><b>Tweet Map</b></div>
             <div id="map_canvas" style='width: 100%; height: 240px';></div> 
		</div>

		
		<div style="clear: both;"></div>
{% endif %}
{% endblock content %}

server/templates/twitinfo/display_links.html
{% for link in links %}
<a href="{{link.0}}" target="_blank">{{link.0}}</a> <span style="font-size: small">(cited by {{link.1}})</span><br>
{% endfor %}

server/templates/twitinfo/display_tweets.html
{% for tweet in tweets %}
<div style="border-color: gray; border-style: solid; border-width: 0px 0px 1px 0px; padding: 2px 0px 2px 0px; background-color: 
{% if tweet.sentiment > 0 %}
rgba(69,175,226,.25);
{% else %} {% if tweet.sentiment < 0 %}
rgba(220,57,18,.25);
{% else %}
rgb(255,255,255);
{% endif %}{% endif %}
">
<div style="float: left;">
<img border="0" src={{tweet.profile_image_url}} width="40" height="40"/>
</div>
{{tweet.tweet}}
<div style="clear: both;"></div>
</div>
{% endfor %}

server/templates/twitinfo/results.html
{% extends "twitinfo/base.html" %}
{% block content %}

{% if error %}<p><strong>{{ error }}
<!--<a href="/create_event">click here</a>--></strong></p>
  {% else %}
<!--	<p>If you can't find the link you are looking for, <a href="/create_event">click here</a> to create a new event</p>-->
	<h4>The suggested links are:</h4>
		{% for event in events %}
			<ul>
				<li><a href="/detail/{{event.id}}">{{event.name}}</a></li>
			</ul>
		{% endfor %}
{% endif %}
<p>To request a new topic be added to TwitInfo, <a href="mailto:twitinfo@csail.mit.edu">email us</a>!</p>
{% endblock %}

server/templates/twitinfo/twitinfo.html
<html>
<head>

<style type="text/css">

input#button{
 background-color :#D3D3D3;
 border : 1px solid #000;
 font-family: verdana;
 font-size: 15px;
 }

div#bottom {
    margin-top: 95px;
    border-bottom: 1px solid grey;
}
div#hd #heading {
	

	color:0099FF;
    margin-top: 20;
    padding-top: 40;
	font-size:60pt;
    
}

.textInput
{
width: 500px;
height: 28px;
}

span.ex {color:00FF33;}
</style>
</head>

<body>

<div id="hd" align=center>

    <div id="heading">twitInfo</div>
    <p>Find out what Twitter thinks about anything.</p>
    Featured topics:<br />
    {% for event in featured %}
        <a href="/detail/{{event.id}}">{{event.name}}</a><br />
    {% endfor %}
<!--    <form action="/results" method="get">
        <p>
		  <input name="query" type="textbox" class="textInput">
		</p>
		<p>
		  <input id="button" type="submit" value="Search" >
        </p>
    </form>-->
</div>
<br><br><br>
<p>
twitInfo is a tool which tracks keyword mentions on Twitter and turns them
into timeline visualizations which summarize various topics.  To learn
more, read our <a
href="http://people.csail.mit.edu/marcua/papers/twitinfo-chi2011.pdf">CHI
2011 paper</a> or send us <a href="mailto:twitinfo@csail.mit.edu">an email</a>.
</p>



</body>
</html>